
package view;

import controller.BasicModeController;
import model.CalculatorComplexNumber;
import model.ComplexNumber;

public class BasicModePanel extends javax.swing.JPanel {
    private final BasicModeController controller;
    private final ComplexNumber cplxModel;

    private final CalculatorComplexNumber cplxCalc;


    /**
     * Creates new form BasicModePanel
     */
    public BasicModePanel() {    
        cplxModel = new ComplexNumber();
        cplxCalc = new CalculatorComplexNumber();
        controller= new BasicModeController(this,cplxModel,cplxCalc);
        initComponents();
        onClickBtn();
        
    }
    
    public void alert(String text) {
        alert1BasicModeLabel.setText(text);
    }
    
    public void setInputFieldText(String text) {
        inputField.setText(text);
    }
    
     public void setResultFieldText(String text) {
        resultField.setText(text);
    }
     
    public void setResultListFieldText(String text){
        resultListField.setText(text);
    }
    public String getInputFieldText() {
        return inputField.getText();
    }
     public String getResultListFieldText() {
        return resultListField.getText();
    }
     
    

    public void onClickBtn(){
         btn0.addActionListener(controller);
         btn1.addActionListener(controller);
         btn2.addActionListener(controller);
         btn3.addActionListener(controller);
         btn4.addActionListener(controller);
         btn5.addActionListener(controller);
         btn6.addActionListener(controller);
         btn7.addActionListener(controller);
         btn8.addActionListener(controller);
         btn9.addActionListener(controller);
         addBtn.addActionListener(controller);
         minusBtn.addActionListener(controller);
         multiBtn.addActionListener(controller);
         divideBtn.addActionListener(controller);
         dotBtn.addActionListener(controller);
         imaginBtn.addActionListener(controller);
         ansBtn.addActionListener(controller);
         openParenthesisBtn.addActionListener(controller);
         closeParenthesisBtn.addActionListener(controller);
         delBtn.addActionListener(controller);
         clearBtn.addActionListener(controller);
         equalBtn.addActionListener(controller);
         saveBtn.addActionListener(controller);
         openBtn.addActionListener(controller);
         cancleBtn.addActionListener(controller);

         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultListField = new javax.swing.JTextArea();
        resultField = new javax.swing.JTextField();
        calcBtns = new javax.swing.JPanel();
        emptyBtn1 = new javax.swing.JButton();
        emptyBtn2 = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        openParenthesisBtn = new javax.swing.JButton();
        closeParenthesisBtn = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        multiBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        imaginBtn = new javax.swing.JButton();
        ansBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        alert1BasicModeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        openBtn = new javax.swing.JButton();
        cancleBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));

        basicPanel.setBackground(new java.awt.Color(51, 153, 255));
        basicPanel.setMaximumSize(new java.awt.Dimension(850, 480));
        basicPanel.setPreferredSize(new java.awt.Dimension(850, 480));

        inputField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        inputField.setToolTipText("");
        inputField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        resultListField.setColumns(20);
        resultListField.setRows(5);
        jScrollPane1.setViewportView(resultListField);

        resultField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        calcBtns.setBackground(new java.awt.Color(51, 153, 255));
        calcBtns.setAutoscrolls(true);
        calcBtns.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calcBtns.setLayout(new java.awt.GridLayout(5, 5));

        emptyBtn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        calcBtns.add(emptyBtn1);

        emptyBtn2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        calcBtns.add(emptyBtn2);

        emptyBtn3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        calcBtns.add(emptyBtn3);

        delBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        delBtn.setText("DEL");
        calcBtns.add(delBtn);

        clearBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        clearBtn.setText("C");
        clearBtn.setToolTipText("");
        calcBtns.add(clearBtn);

        btn7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn7.setText("7");
        calcBtns.add(btn7);

        btn8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn8.setText("8");
        calcBtns.add(btn8);

        btn9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn9.setText("9");
        calcBtns.add(btn9);

        openParenthesisBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        openParenthesisBtn.setText("(");
        calcBtns.add(openParenthesisBtn);

        closeParenthesisBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        closeParenthesisBtn.setText(")");
        calcBtns.add(closeParenthesisBtn);

        btn4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn4.setText("4");
        calcBtns.add(btn4);

        btn5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn5.setText("5");
        calcBtns.add(btn5);

        btn6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn6.setText("6");
        calcBtns.add(btn6);

        addBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addBtn.setText("+");
        calcBtns.add(addBtn);

        minusBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        minusBtn.setText("-");
        calcBtns.add(minusBtn);

        btn1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn1.setText("1");
        calcBtns.add(btn1);

        btn2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn2.setText("2");
        calcBtns.add(btn2);

        btn3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn3.setText("3");
        calcBtns.add(btn3);

        multiBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        multiBtn.setText("*");
        calcBtns.add(multiBtn);

        divideBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        divideBtn.setText("/");
        calcBtns.add(divideBtn);

        btn0.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn0.setText("0");
        calcBtns.add(btn0);

        dotBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        dotBtn.setText(".");
        calcBtns.add(dotBtn);

        imaginBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        imaginBtn.setText("i");
        calcBtns.add(imaginBtn);

        ansBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        ansBtn.setText("Ans");
        calcBtns.add(ansBtn);

        equalBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        equalBtn.setText("=");
        equalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        equalBtn.setDefaultCapable(false);
        equalBtn.setMaximumSize(new java.awt.Dimension(64, 32));
        equalBtn.setMinimumSize(new java.awt.Dimension(64, 32));
        equalBtn.setPreferredSize(new java.awt.Dimension(64, 32));
        equalBtn.setRolloverEnabled(false);
        calcBtns.add(equalBtn);

        alert1BasicModeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        alert1BasicModeLabel.setForeground(new java.awt.Color(255, 255, 102));

        jLabel3.setBackground(new java.awt.Color(0, 153, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Chức năng cơ bản");

        saveBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        saveBtn.setText("SAVE");

        openBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        openBtn.setText("OPEN");

        cancleBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        cancleBtn.setText("CANCLE");

        javax.swing.GroupLayout basicPanelLayout = new javax.swing.GroupLayout(basicPanel);
        basicPanel.setLayout(basicPanelLayout);
        basicPanelLayout.setHorizontalGroup(
            basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicPanelLayout.createSequentialGroup()
                        .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputField)
                            .addGroup(basicPanelLayout.createSequentialGroup()
                                .addComponent(calcBtns, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(basicPanelLayout.createSequentialGroup()
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addComponent(cancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(resultField)
                                    .addComponent(jScrollPane1))))
                        .addGap(16, 16, 16))
                    .addGroup(basicPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(alert1BasicModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        basicPanelLayout.setVerticalGroup(
            basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basicPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(alert1BasicModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicPanelLayout.createSequentialGroup()
                        .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calcBtns, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(basicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(basicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
  
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel alert1BasicModeLabel;
    private javax.swing.JButton ansBtn;
    private javax.swing.JPanel basicPanel;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JPanel calcBtns;
    private javax.swing.JButton cancleBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeParenthesisBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton emptyBtn1;
    private javax.swing.JButton emptyBtn2;
    private final javax.swing.JButton emptyBtn3 = new javax.swing.JButton();
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton imaginBtn;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton multiBtn;
    private javax.swing.JButton openBtn;
    private javax.swing.JButton openParenthesisBtn;
    private javax.swing.JTextField resultField;
    private javax.swing.JTextArea resultListField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

}
