/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Mode3AdvanceController;
import model.ComplexNumber;

/**
 *
 * @author Manht
 */
public class Mode3AdvancePanel extends javax.swing.JPanel {

    private final Mode3AdvanceController controller;
    private Mode3AdvancePanel view;
    private final ComplexNumber model;
    /**
     * Creates new form Mode3AdvancePanel
     */
    public Mode3AdvancePanel() {
        initComponents();
        model=new ComplexNumber();
        controller=new Mode3AdvanceController(this, model);
        calcMode3Btn.addActionListener(controller);
    }
    
    public double getRealValueMode3(){
        return Double.parseDouble(real1Mode3Input.getText());
    }
    
    public double getImagValueMode3(){
        return Double.parseDouble(imag1Mode3Input.getText());
    }
    
    public int getExplValueMode3(){
        return Integer.parseInt(exp1Mode3Input.getText());
    }
    
    public void alert(String text){
        alert3Label.setText(text);
    }
    public void setLabel1(String text) {
        z1Mode3Label.setText(text);
    }
    
    public void setLabel2(String text) {
        z2Mode3Label.setText(text);
    }
    
    public void setLabel3(String text) {
        z3Mode3Label.setText(text);
    }
    
    public void setLabel4(String text) {
        z4Mode3Label.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        imag1Mode3Input = new javax.swing.JTextField();
        z5Mode3Label = new javax.swing.JLabel();
        real1Mode3Input = new javax.swing.JTextField();
        z4Mode3Label = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        z3Mode3Label = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        z2Mode3Label = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        alert3Label = new javax.swing.JLabel();
        z1Mode3Label = new javax.swing.JLabel();
        calcMode3Btn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        exp1Mode3Input = new javax.swing.JTextField();

        jLabel31.setText("----------------------------------------------------------------------------------------------------------------");

        jLabel29.setText("Nhập số mũ (n)");

        imag1Mode3Input.setText("4");

        real1Mode3Input.setText("3");

        jLabel28.setText("Nhập phần ảo (b)");

        jLabel27.setText("Nhập phần thực (a)");

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel26.setText("Số phức mũ bậc cao  ");

        alert3Label.setForeground(new java.awt.Color(255, 51, 51));

        calcMode3Btn.setText("Tính toán");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel30.setText("z=a+bi. Tính z^n");

        exp1Mode3Input.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addGap(43, 43, 43)
                            .addComponent(alert3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(real1Mode3Input, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(exp1Mode3Input))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(imag1Mode3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(calcMode3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(z2Mode3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z3Mode3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z4Mode3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z5Mode3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z1Mode3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(alert3Label))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(real1Mode3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(imag1Mode3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(exp1Mode3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcMode3Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(z1Mode3Label)
                .addGap(24, 24, 24)
                .addComponent(z2Mode3Label)
                .addGap(24, 24, 24)
                .addComponent(z3Mode3Label)
                .addGap(24, 24, 24)
                .addComponent(z4Mode3Label)
                .addGap(24, 24, 24)
                .addComponent(z5Mode3Label)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert3Label;
    private javax.swing.JButton calcMode3Btn;
    private javax.swing.JTextField exp1Mode3Input;
    private javax.swing.JTextField imag1Mode3Input;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JTextField real1Mode3Input;
    private javax.swing.JLabel z1Mode3Label;
    private javax.swing.JLabel z2Mode3Label;
    private javax.swing.JLabel z3Mode3Label;
    private javax.swing.JLabel z4Mode3Label;
    private javax.swing.JLabel z5Mode3Label;
    // End of variables declaration//GEN-END:variables
}
