
package view;

import controller.Mode5AdvanceController;
import controller.Mode6AdvanceController;
import model.ComplexNumber;

public class Mode6AdvancePanel extends javax.swing.JPanel {

    private final Mode6AdvanceController controller;
    private Mode6AdvancePanel view;
    private final ComplexNumber model;
    /**
     * Creates new form Mode6AdvancePanel
     */
    public Mode6AdvancePanel() {
        initComponents();
        model=new ComplexNumber();
        controller=new Mode6AdvanceController(this, model);
        totalMode6Btn.addActionListener(controller);
        intensiteMode6Btn.addActionListener(controller);
        rcCircuitBtn.addActionListener(controller);
        lcCircuitBtn.addActionListener(controller);
    }
    //Giá trị của U
    public String getVoltageValue(){
        return voltageInput.getText();
    }
    
    //tần số góc
    public String getOmegaValue(){
        return omegaInput.getText();
    }
    
    //Giá trị góc
    public String getAngleValue(){
        return angleInput.getText();
    }
    
   //resistor: điện trở R
    public String getResistorValue(){
        return resistorInput.getText();
    }
    
    //inductance : độ tự cảm
    public String getInductanceValue(){
        return inductanceInput.getText();
    }
    
    //capacitance: điện dung
    public String getCapacitanceValue(){
        return capacitanceInput.getText();
    }
    
    
    public void setLabel1(String text) {
        z1Mode6Label.setText(text);
    }
    
    public void setLabel2(String text) {
        z2Mode6Label.setText(text);
    }
    
    public void setLabel3(String text) {
        z3Mode6Label.setText(text);
    }
    
    public void setLabel4(String text) {
        z4Mode6Label.setText(text);
    }
    
    public void alert(String text) {
        alert1Mode6Label.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        omegaInput = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        resistorInput = new javax.swing.JTextField();
        angleInput = new javax.swing.JTextField();
        resistorLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        z1Mode6Label = new javax.swing.JLabel();
        lcCircuitBtn = new javax.swing.JButton();
        rcCircuitBtn = new javax.swing.JButton();
        totalMode6Btn = new javax.swing.JButton();
        intensiteMode6Btn = new javax.swing.JButton();
        capacitanceInput = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        alert1Mode6Label = new javax.swing.JLabel();
        inductanceInput = new javax.swing.JTextField();
        z4Mode6Label = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        z3Mode6Label = new javax.swing.JLabel();
        z2Mode6Label = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        voltageInput = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();

        omegaInput.setText("100");
        omegaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omegaInputActionPerformed(evt);
            }
        });

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel63.setText("ω =");

        jLabel59.setText("deg");

        jLabel58.setText("V");

        resistorInput.setText("100");
        resistorInput.setToolTipText("");

        angleInput.setText("45");

        resistorLabel.setText("Điện trở R (Ω)");

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel24.setText("Mạch RLC - Điện xoay chiều");

        lcCircuitBtn.setText("điện áp LC");

        rcCircuitBtn.setText("điện áp RC");

        totalMode6Btn.setText("Tính tổng trở");

        intensiteMode6Btn.setText("biểu thức dòng điện");

        capacitanceInput.setText("15.9");

        jLabel52.setText("Điện dung C (μF) ");

        alert1Mode6Label.setForeground(new java.awt.Color(255, 51, 51));
        alert1Mode6Label.setText("a");

        inductanceInput.setText("0.318");

        jLabel25.setText("Độ tự cảm L (H)");

        z3Mode6Label.setToolTipText("");

        jLabel65.setText("---------------------------------------------------------------------------------------------------------------------------");

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setText("φu=");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel56.setText("Tính điện áp hai đầu đoạn mạch RC và LC ?");

        voltageInput.setText("200");

        jLabel55.setText("U0 =");

        jLabel53.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel53.setText("Điện áp hai đầu mạch u = U0*cos(ωt + φu) có giá trị R=?, L=?, C=?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resistorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resistorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(voltageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inductanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(omegaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(capacitanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(angleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alert1Mode6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalMode6Btn)
                                .addGap(16, 16, 16)
                                .addComponent(intensiteMode6Btn)
                                .addGap(16, 16, 16)
                                .addComponent(rcCircuitBtn)
                                .addGap(16, 16, 16)
                                .addComponent(lcCircuitBtn))
                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(z4Mode6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(z3Mode6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(z1Mode6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(z2Mode6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(alert1Mode6Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(voltageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(angleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59)
                    .addComponent(jLabel63)
                    .addComponent(omegaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resistorLabel)
                    .addComponent(jLabel25)
                    .addComponent(resistorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inductanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(capacitanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intensiteMode6Btn)
                    .addComponent(totalMode6Btn)
                    .addComponent(rcCircuitBtn)
                    .addComponent(lcCircuitBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(z1Mode6Label)
                .addGap(18, 18, 18)
                .addComponent(z2Mode6Label)
                .addGap(18, 18, 18)
                .addComponent(z3Mode6Label)
                .addGap(18, 18, 18)
                .addComponent(z4Mode6Label)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void omegaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omegaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_omegaInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert1Mode6Label;
    private javax.swing.JTextField angleInput;
    private javax.swing.JTextField capacitanceInput;
    private javax.swing.JTextField inductanceInput;
    private javax.swing.JButton intensiteMode6Btn;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JButton lcCircuitBtn;
    private javax.swing.JTextField omegaInput;
    private javax.swing.JButton rcCircuitBtn;
    private javax.swing.JTextField resistorInput;
    private javax.swing.JLabel resistorLabel;
    private javax.swing.JButton totalMode6Btn;
    private javax.swing.JTextField voltageInput;
    private javax.swing.JLabel z1Mode6Label;
    private javax.swing.JLabel z2Mode6Label;
    private javax.swing.JLabel z3Mode6Label;
    private javax.swing.JLabel z4Mode6Label;
    // End of variables declaration//GEN-END:variables
}
