/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.SelectAdvanceModeController;

/**
 *
 * @author Manht
 */
public class SelectAdvanceModePanel extends javax.swing.JPanel {

    private final SelectAdvanceModeController controller;
    
    public SelectAdvanceModePanel(AdvanceModePanel advanceModePanel) {
        controller=new SelectAdvanceModeController(advanceModePanel);
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mode1Btn = new javax.swing.JButton();
        mode2Btn = new javax.swing.JButton();
        mode3Btn = new javax.swing.JButton();
        mode4Btn = new javax.swing.JButton();
        mode5Btn = new javax.swing.JButton();
        mode6Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));

        mode1Btn.setText("Phân tích số phức");
        mode1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode1BtnActionPerformed(evt);
            }
        });

        mode2Btn.setText("Tìm nghiệm phức");
        mode2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode2BtnActionPerformed(evt);
            }
        });

        mode3Btn.setText("Mũ bậc cao");
        mode3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode3BtnActionPerformed(evt);
            }
        });

        mode4Btn.setText("Khai căn bậc cao");
        mode4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode4BtnActionPerformed(evt);
            }
        });

        mode5Btn.setText("Tổng hợp dao động");
        mode5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode5BtnActionPerformed(evt);
            }
        });

        mode6Btn.setText("Mạch RLC");
        mode6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode6BtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Vật Lý");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Toán học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mode1Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(mode2Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mode5Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(mode6Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mode4Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mode3Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(mode1Btn)
                .addGap(18, 18, 18)
                .addComponent(mode2Btn)
                .addGap(18, 18, 18)
                .addComponent(mode3Btn)
                .addGap(18, 18, 18)
                .addComponent(mode4Btn)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mode5Btn)
                .addGap(18, 18, 18)
                .addComponent(mode6Btn)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mode2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode2BtnActionPerformed
        // TODO add your handling code here:
        controller.mode2Click();
    }//GEN-LAST:event_mode2BtnActionPerformed

    private void mode1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode1BtnActionPerformed
        // TODO add your handling code here:
        controller.mode1Click();
    }//GEN-LAST:event_mode1BtnActionPerformed

    private void mode3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode3BtnActionPerformed
        // TODO add your handling code here:
        controller.mode3Click();
    }//GEN-LAST:event_mode3BtnActionPerformed

    private void mode4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode4BtnActionPerformed
        // TODO add your handling code here:
        controller.mode4Click();
    }//GEN-LAST:event_mode4BtnActionPerformed

    private void mode5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode5BtnActionPerformed
        // TODO add your handling code here:
        controller.mode5Click();
    }//GEN-LAST:event_mode5BtnActionPerformed

    private void mode6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode6BtnActionPerformed
        // TODO add your handling code here:
        controller.mode6Click();
    }//GEN-LAST:event_mode6BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mode1Btn;
    private javax.swing.JButton mode2Btn;
    private javax.swing.JButton mode3Btn;
    private javax.swing.JButton mode4Btn;
    private javax.swing.JButton mode5Btn;
    private javax.swing.JButton mode6Btn;
    // End of variables declaration//GEN-END:variables
}
